### ISSUE TITLE
Question: What's the status of Core Direct?

### ISSUE THREAD

**Issue by BKitor** [openucx/ucc#354]
I realize I'm about a decade out late, but is Core Direct still a thing, and will UCC be using it?
I've been trying to find information on core direct, but it seems like support got dropped somewhere.
Is there any documentation regarding core direct, or even a header file with the endpoints?

Thanks

**Comment by vspetrov** [comment]
Hi @BKitor ,
CD as a HW technology is available since CX3 (or maybe even CX2) but the SW support has been dropped due to limitations and lack of production use-cases and is no longer available for MOFED versions >= 5.x. Only old Mofeds (4.x) have an "experimental verbs" (verbs_exp.h) public interface that allows programming CD. Here is the example how those APIs could be used https://github.com/mellanox-hpc/coredirect/tree/master/examples.

UCC is not going to support CD because of that. The "offload" technology is still considered very important piece for HPC performance. But it will be enabled using other HW features (e.g. bluefield DPU - user ifaces to be defined).

**Comment by BKitor** [comment]
@vspetrov Thanks, that really clears things up.
