### ISSUE TITLE
Include #847 in v1.3.0 RC

### ISSUE THREAD

**Issue by sandeepd-nv** [openucx/ucc#947]
Hi, please consider including PR [#847 ](https://github.com/openucx/ucc/pull/847) in v1.3.0 RC. I am not able to build v1.2.0 or v.1.3.0-rc1 with CUDA. Either nvcc hangs on certain files or it errors out due to the issue addressed in the aforementioned PR.

**Comment by Sergei-Lebedev** [comment]
Hi @sandeepd-nv, this PR already included into v1.3.0. Please keep in mind that if you build UCC with default options it might take a lot of time to compile it since we need to build all combinations of reductions and GPU archs. You can use --with-nvcc-gencode option to reduce compilation time (https://github.com/openucx/ucc/wiki/FAQ#15-how-to-compile-ucc-for-a-specific-gpu-architecture)

**Comment by sandeepd-nv** [comment]
Thanks, @Sergei-Lebedev!
